name: Build Status

on:
  push:
    branches:
       - main
  pull_request:
  schedule:
    - cron:  '0 0 * * 0'
  workflow_dispatch:

concurrency:
   group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
   cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -e .[dev]
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make tests
